### ISSUE TITLE
Cant change knives and sometimes unable to load skins.

### ISSUE THREAD

**Issue by Soramagic7** [ianlucas/cs2-inventory-simulator-plugin#9]
21:20:09 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[T](IntPtr function, Object[] arguments) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1090
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.MemoryFunctionWithReturn`3.Invoke(T1 arg1, T2 arg2) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/MemoryFunctionWithReturn.cs:line 58
   at InventorySimulator.InventorySimulator.GivePlayerWeaponSkin(CCSPlayerController player, CBasePlayerWeapon weapon) in C:\Users\ianlu\Projects\cs2-inventory-simulator-plugin\source\InventorySimulator\InventorySimulator.Give.cs:line 109
   at InventorySimulator.InventorySimulator.OnGiveNamedItemPost(DynamicHook hook) in C:\Users\ianlu\Projects\cs2-inventory-simulator-plugin\source\InventorySimulator\InventorySimulator.Hooks.cs:line 25
   at InvokeStub_Func`2.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
21:20:10 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[T](IntPtr function, Object[] arguments) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1090
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.MemoryFunctionWithReturn`3.Invoke(T1 arg1, T2 arg2) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/MemoryFunctionWithReturn.cs:line 58
   at InventorySimulator.InventorySimulator.GivePlayerWeaponSkin(CCSPlayerController player, CBasePlayerWeapon weapon) in C:\Users\ianlu\Projects\cs2-inventory-simulator-plugin\source\InventorySimulator\InventorySimulator.Give.cs:line 109
   at InventorySimulator.InventorySimulator.<>c__DisplayClass45_0.<OnEntityCreated>b__0() in C:\Users\ianlu\Projects\cs2-inventory-simulator-plugin\source\InventorySimulator\InventorySimulator.Listeners.cs:line 36
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

Fix it plz, thanks!

**Comment by Soramagic7** [comment]
it works fine in windows but not in linux, I'm using beta28, i think it's gamedata expired probably.

**Comment by ianlucas** [comment]
Thanks for reporting.

https://github.com/ianlucas/cs2-inventory-simulator-plugin/releases/tag/v1.0.0-beta.29

**Comment by Soramagic7** [comment]
it works fine now, thanks for ur update!
